### PR TITLE
Percy screenshots and adjusted Cypress

### PR DESCRIPTION
**Pull request by coopjakob**

### CODE REVIEW

**Comment by benjick** [comment]
See these settings for the e2e runner: https://github.com/vegans/totalinsyn.nu/blob/master/.github/workflows/main.yml#L37-L41

**Comment by coopjakob** [comment]
> See these settings for the e2e runner: https://github.com/vegans/totalinsyn.nu/blob/master/.github/workflows/main.yml#L37-L41

Any different from this?
```
      - name: Percy Test
        uses: percy/exec-action@v0.3.0
        with:
          command: "cypress run"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
```

**Comment by benjick** [comment]
Oh sorry, didn't see that!

**Comment by coopjakob** [comment]
> Oh sorry, didn't see that!

It's from the docs. But I've added your version of it for now.

**Comment by coopjakob** [comment]
Screenshot 2020-04-06 at 21 58 17
Problem when adding a change request, so I guess we need to change to the `percy/exec-action@v0.3.0`

**Pull request merged**
